version: '3.4'
services: 
  db:
    image: zanoli/mysql-crud-compasso
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: crud_compasso
    ports: 
      - "3308:3308"
    networks: 
      - udemy-networks
  crud-compasso:
    image: zanoli/crud-compasso
    restart: always
    build: ./crud
    working_dir: /crud
    environment: 
        TZ: America/Sao_Paulo
        SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./crud:/crud
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    command: mvn clean spring-boot:run
    links: 
      - db
    depends_on:  
      - db
    networks: 
      - udemy-networks
networks: 
    udemy-networks:
      driver: bridge